In [1]:
# array oriented programing with NumPy

In [2]:
import numpy as np

In [3]:
numbers=np.array([2,3,5,7,11])

In [4]:
type(numbers)

numpy.ndarray

In [5]:
numbers

array([ 2,  3,  5,  7, 11])

In [7]:
np.array([[1,2,3],[4,5,6]]) # two dimentional array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
numbers1=np.array([i for i in range(10) ])

In [14]:
numbers1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
integers=np.array([[1,2,3],[4,5,6]]) 

In [16]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
floats=np.array([0.0,0.1,0.2,0.3,0.4])

In [21]:
floats   # by default it not shows trailing zeros , that is why it diaplyed 0. in below 

array([0. , 0.1, 0.2, 0.3, 0.4])

In [22]:
numbers.dtype # cehck datatype

dtype('int32')

In [23]:
floats.dtype

dtype('float64')

In [25]:
integers.ndim  # it retuen no of dimentions , this is integers is an two dimentional array

2

In [27]:
numbers.ndim

1

In [29]:
floats.ndim

1

In [30]:
integers.shape  # it says it has 2 rows and 3 colums in the arrau

(2, 3)

In [31]:
numbers.shape  # for single dimentional array it retun no of elements 

(5,)

In [32]:
floats.shape

(5,)

In [33]:
integers.size # it retun the total elements , whcihs is 2 rows and 3 columsn so total 6

6

In [34]:
numbers.size

5

In [35]:
integers.itemsize   # how many bites it uses to store the each element 

4

In [36]:
# loop

In [38]:
for row in integers:
    for column in row:
        print(column,end= ' ')
    print() # empty print for new line character

1 2 3 
4 5 6 


In [39]:
for row in integers:
    for column in row:
        print(column,end= ' ')
  #  print() # empty print for new line character

1 2 3 4 5 6 

In [40]:
# we can iterate the multi deimentional array as one dimentional array 
# by using this flat we can do it 
# it flaten out the mutidimentional array 
# first it takes first row and after that it takes the second row and sticks to the first row and so on ...

In [41]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [45]:
np.zeros(5) # it create arry of 5 zeros and by default it create floating numbers 

array([0., 0., 0., 0., 0.])

In [46]:
np.ones((2,4),dtype=int)  # here we said create arry with 1 and with 2 rows and 4 columns and mentioned dataype shoube be integer

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.full((3,5),13)  # if you want array some random number we have this full , so we can mention the rows and olumn and 
# second argument as the number that we want

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [1]:
# ranges of values and turning them into arrays 

In [3]:
import numpy as np

In [5]:
np.arange(5)   # numpy has this function to range of values in a list 

array([0, 1, 2, 3, 4])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [7]:
np.arange(10,1,-2)  # 10 to 1 (not including 1) decrement by -2 

array([10,  8,  6,  4,  2])

In [9]:
np.linspace(0.0,0.5,num=5) # this is to generate floating point numbers
# start with 0.0 and end with 0.5 and total nof of elements should be 5

array([0.   , 0.125, 0.25 , 0.375, 0.5  ])

In [8]:
np.linspace(0.0,0.5,num=10)

array([0.        , 0.05555556, 0.11111111, 0.16666667, 0.22222222,
       0.27777778, 0.33333333, 0.38888889, 0.44444444, 0.5       ])

In [10]:
# generate a range and convert into multi dimetional array

In [14]:
np.arange(1,21).reshape(4,5)  # range of values from 1 to 21(not including 21)
# and reshate to multi dimentional array with 4 rows and 5 columns 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
np.arange(1,100001).reshape(4,25000)  # if is more than 1000 elements np sumarises the outupt like below ...

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [16]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [ ]:
# self check 

In [18]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [19]:
np.arange(2,41,2).size

20

In [20]:
# list vs  numpy array performance 

In [22]:
# %timeit  this will give the how much time it took to execute the command
# not only that it try to execute many times and gives you the avg time 

In [23]:
import random

In [26]:
rolls_list=[random.randrange(1,7) for i in range(6_000_000)]  # list comprehension

In [27]:
%timeit rolls_list=[random.randrange(1,7) for i in range(6_000_000)]

3.8 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
%timeit rolls_list=np.random.randint(1,7,6_000_000)  # numpy buitin function 

59.5 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
# see the above difference numpy is faster than normal list 

In [30]:
%timeit -n3 -r2 rolls_list=np.random.randint(1,7,6_000_000)  
# here we are specifying the how rune and loops it should do -n3: loops , -r2: runs 

67.1 ms ± 6.75 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [31]:
# self cehck 

In [32]:
%timeit sum([x for x in range(10_000_000)])

741 ms ± 54.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%timeit np.arange(10_000_000).sum()

17.3 ms ± 589 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
# array operators 

In [35]:
numbers=np.arange(1,6)

In [36]:
numbers

array([1, 2, 3, 4, 5])

In [37]:
# in regular list we nned to itere thouh elment to do any operation ,
# here we no nned to do 

In [38]:
numbers*2  # it multiplied every element in the array 

array([ 2,  4,  6,  8, 10])

In [39]:
numbers**3  # currenlty we are just displaying the value not updating the values 

array([  1,   8,  27,  64, 125], dtype=int32)

In [40]:
numbers

array([1, 2, 3, 4, 5])

In [41]:
numbers+=10

In [43]:
numbers

array([11, 12, 13, 14, 15])

In [44]:
numbers2=np.linspace(1.1,5.5,5)  # floating number array

In [45]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [46]:
numbers*numbers2 # elements in each array shoule be same dimention 

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [48]:
numbers

array([11, 12, 13, 14, 15])

In [49]:
numbers>=13 # return new array with values 

array([False, False,  True,  True,  True])

In [50]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [51]:
numbers2<numbers

array([ True,  True,  True,  True,  True])

In [52]:
numbers== numbers2

array([False, False, False, False, False])

In [54]:
numbers==numbers

array([ True,  True,  True,  True,  True])

In [55]:
# self cehck 

In [56]:
number3=np.arange(1,5)

In [57]:
number3*2

array([2, 4, 6, 8])

In [58]:
number3

array([1, 2, 3, 4])

In [ ]:
# below is in a single line 

In [59]:
np.arange(1,5)*2

array([2, 4, 6, 8])

In [60]:
# numpy calculation methods 

In [62]:
grades=np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])

In [63]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [64]:
grades.sum()

1054

In [65]:
grades.min()

70

In [66]:
grades.max()

100

In [67]:
grades.mean() # this is average 

87.83333333333333

In [68]:
grades.std() # standard deviation

8.792357792739987

In [69]:
grades.var()  # varience 

77.30555555555556

In [70]:
# so far the above mentioned performed on entire array , what if we need to perform on perticula column or row 

In [71]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [72]:
grades.mean(axis=0)  # here the axis=0 means column 

array([95.25, 85.25, 83.  ])

In [73]:
# so here 95.25 is the avg of first column  and 85.25 is the avg of second column so on .. 

In [74]:
grades.mean(axis=1)  # here the axis=1 means row 

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [79]:
grades.mean? # documentation for mean method

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method


In [80]:
# self cehck 

In [81]:
grades3=np.random.randint(60,101,12).reshape(3,4)  # start with 60 to 100 and 12 random numbers 

In [82]:
grades3

array([[95, 93, 69, 81],
       [99, 78, 76, 88],
       [92, 84, 88, 93]])

In [83]:
grades3.mean()

87.83333333333333

In [86]:
grades3.mean(axis=0)  # column avg , 4 columns so 4 avg values in te result 

array([95.33333333, 85.        , 77.66666667, 87.33333333])

In [87]:
grades3.mean(axis=1) # row avg  , 3 rows so 3 avg values 

array([84.5 , 85.25, 89.25])

In [1]:
#  Numpy universal functions 

In [2]:
import numpy as np

In [3]:
numbers =np.array([1,4,9,16,25,36])

In [4]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [5]:
numbers2=np.arange(1,7)*10 # arange is similar to range that create elements from 1 to 7 
# arange is numpy functiom 

In [6]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [7]:
np.add(numbers,80) # so it add 80 to the all each individual element in numbers array

array([ 81,  84,  89,  96, 105, 116])

In [8]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [10]:
np.add(numbers,numbers2)  # it add each element from  both the arrys 

array([11, 24, 39, 56, 75, 96])

In [11]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [12]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [13]:
numbers3=numbers.reshape(2,3) # this should match up with the no of elements

In [14]:
numbers3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [15]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [17]:
numbers4=np.array([2,4,6])

In [20]:
numbers3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [22]:
numbers4

array([2, 4, 6])

In [23]:
np.multiply(numbers3,numbers4)  # multiply with multile arrays , make sure the column size( 3 columns ) mush match 

array([[  2,  16,  54],
       [ 32, 100, 216]])

In [24]:
# indexing and slicing Numpy arrays 

In [33]:
grades=np.array([[87,96,70],[100,87,90],
                [94,77,90],[100,81,82]]) # multi  deimentional array 


In [34]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [31]:
grades[0,1] # which means row 0 column 1 

96

In [32]:
grades[0,2] # row 0 column 2

70

In [35]:
grades[0,2]

70

In [36]:
grades[0,0]

87

In [37]:
grades[1]  # row number 1

array([100,  87,  90])

In [39]:
grades[1,2] # row 1 column 2 

90

In [41]:
grades[0:2] # here in this clicing , start from row 0 to row 2(not include 2) 

array([[ 87,  96,  70],
       [100,  87,  90]])

In [42]:
grades[[1,3]] # this is to get multiple rows [[]]  , row number 1 and row number 3 

array([[100,  87,  90],
       [100,  81,  82]])

In [43]:
# above all reprasent rows , now lets do with columns 

In [44]:
grades[:,0]   # this is all rows in the column 0 , but here the column value disaplyes in hirizatally 

array([ 87, 100,  94, 100])

In [45]:
grades[:,1] # all rows in column 1 

array([96, 87, 77, 81])

In [46]:
grades[:,1:3] # all rows from column 1 to colimn 3 ( not include 3)

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [47]:
grades[1,1:3]  # row number 1 from column 1 to column 3 ( not include 3 )

array([87, 90])

In [49]:
grades[:,[0,2]] # instead providing ramge in slice we can provide the columns that we wanted inside [[]]
# so here we are saying all the rows from column 0 and 2 

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [50]:
# view : shallow copies 

In [52]:
numbers=np.arange(1,6)

In [53]:
numbers

array([1, 2, 3, 4, 5])

In [56]:
numbers2=numbers.view()

In [57]:
numbers2

array([1, 2, 3, 4, 5])

In [58]:
id(numbers)

1935637411856

In [59]:
id(numbers2)

1935676578288

In [60]:
numbers[1]*=10

In [61]:
numbers2  # though we updated the numbers array the change is reflected in numbers2 as well

array([ 1, 20,  3,  4,  5])

In [62]:
numbers2[1]/=10

In [63]:
numbers2

array([1, 2, 3, 4, 5])

In [64]:
numbers   # though we updated the numbers2 array the change is reflected in numbers as well ( like oracle view )

array([1, 2, 3, 4, 5])

In [65]:
numbers2=numbers[0:3] # here it create a view with only first 3 elemenst 

In [66]:
numbers2

array([1, 2, 3])

In [67]:
numbers

array([1, 2, 3, 4, 5])

In [68]:
id(numbers)

1935637411856

In [69]:
id(numbers2)

1935675746224

In [70]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [71]:
numbers[1]*=20 # since we updated the item in the index 1 ,we can see the same resuklt in view numbers2

In [72]:
numbers

array([ 1, 40,  3,  4,  5])

In [73]:
numbers2

array([ 1, 40,  3])

In [74]:
# deep copy or physically seperate copy 

In [75]:
numbers

array([ 1, 40,  3,  4,  5])

In [76]:
numbers2=numbers.copy()

In [77]:
numbers2

array([ 1, 40,  3,  4,  5])

In [78]:
numbers[2]*=10

In [79]:
numbers

array([ 1, 40, 30,  4,  5])

In [80]:
numbers2 # since thhis is seperate copy no effect in this array with numbers array update with 10

array([ 1, 40,  3,  4,  5])

In [81]:
# several diff methods on reshaping and transposing numpy array 

In [82]:
grades=np.array([[87,96,70],[100,87,90]])

In [83]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [84]:
grades.reshape(1,6) # please note this reshape is an view , it doesn't modify the original 
# please note it is an two dimentional array [[]]

array([[ 87,  96,  70, 100,  87,  90]])

In [85]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [86]:
grades.resize(1,6) # it actually modify the the array , Please it is still two deimentional 1 row 6 columns array since it has [[]]

In [87]:
grades 

array([[ 87,  96,  70, 100,  87,  90]])

In [88]:
grades=np.array([[87,96,70],[100,87,90]])

In [89]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [90]:
flattened=grades.flatten() # it does two things 1) create a deep copy (create new copy ) and 2) create a single dimentional array []

In [92]:
flattened  # see it is an sindle dimentional array [] , not two dimentional [[]]

array([ 87,  96,  70, 100,  87,  90])

In [93]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [94]:
flattened[0]=100

In [95]:
flattened

array([100,  96,  70, 100,  87,  90])

In [96]:
grades # see the grades not effected by aabove assignment , it proves both are seperate copies

array([[ 87,  96,  70],
       [100,  87,  90]])

In [97]:
raveled =grades.ravel()

In [98]:
raveled # this ravel method also created one dimentional array [], but this is a view/shallow copy , not a original copy

array([ 87,  96,  70, 100,  87,  90])

In [99]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [100]:
raveled[0]=100

In [101]:
raveled

array([100,  96,  70, 100,  87,  90])

In [102]:
grades # see it mofied the original element to 100

array([[100,  96,  70],
       [100,  87,  90]])

In [103]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [104]:
grades.T  # this is tranposing attribute , please note T is caps here 
# this will convert rows into columns and columns into rows ,( like pivot in oracle )

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [ ]:
# please note above is and view / shallow copy 

In [105]:
grades 

array([[100,  96,  70],
       [100,  87,  90]])

In [106]:
# horizantal and vertical stacking of an arrays 

In [107]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [108]:
grades2=np.array([[94,77,90],[100,81,82]])

In [109]:
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [111]:
np.hstack((grades,grades2))  # it accepts a touple , this is horizantal stack , 
# as the name suggest , it stacks the second array horozantally to the first array on the right side 

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [112]:
np.vstack((grades,grades2)) # whcihs is sililar to above but it stack the second array at the end of first array in vertical 

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [113]:
# Data science : Pandas  :-  Series and Dataframe 

In [114]:
import pandas as pd

In [116]:
grades =pd.Series([87,100,94])  # note here S is capital

In [117]:
grades  # here it is showing both indicies and associalted element , it alos shows the datatype

0     87
1    100
2     94
dtype: int64

In [118]:
pd.Series(98.6,range(3))  # we are syaing generate 3 elemensts with the value 98.6

0    98.6
1    98.6
2    98.6
dtype: float64

In [119]:
grades

0     87
1    100
2     94
dtype: int64

In [120]:
grades[0]

87

In [121]:
grades[0:2]

0     87
1    100
dtype: int64

In [122]:
grades.count()

3

In [124]:
grades.mean()

93.66666666666667

In [125]:
grades.min()

87

In [126]:
grades.max()

100

In [127]:
grades.std()

6.506407098647712

In [128]:
grades.describe()  # it wll give you the all the descriptive stats 

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [129]:
# creare a series with custom indicies, index can by any immutable object 

In [133]:
grades=pd.Series([87,100,94], index=['Wally','Eva','Sam'])

In [134]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [135]:
grades['Eva']

100

In [136]:
# craete a serice by using dictonary 

In [137]:
grades=pd.Series({'Wally1':87,'Eva1':100,'Sam1':94})

In [138]:
grades

Wally1     87
Eva1      100
Sam1       94
dtype: int64

In [140]:
grades['Eva1']

100

In [141]:
# another way to access the element in pandas 

In [142]:
grades.Wally1


87

In [143]:
grades.dtype

dtype('int64')

In [144]:
grades.values # this return an Numpy array 

array([ 87, 100,  94], dtype=int64)

In [145]:
hardware=pd.Series(['Hammer','Saw','Wrench'])

In [146]:
hardware

0    Hammer
1       Saw
2    Wrench
dtype: object

In [147]:
# str : string attribute will give more capabilitied in the Series elements 

In [148]:
hardware.str.contains('a') # basically it looks for any element in series contain letter a 
# similar to like operator in oracle , but it retuen boolean

0     True
1     True
2    False
dtype: bool

In [149]:
# massauge data 

In [150]:
hardware.str.upper() # note : it wont modify the original data 

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [151]:
hardware

0    Hammer
1       Saw
2    Wrench
dtype: object

In [152]:
# in Dataframe each column is as Series 

In [153]:
#                                   Panda DataFrames 

In [154]:
# it is and enhanced two deimentional arry , can have custom rows and columns indicies 
#offer additional operations and capabilitied useful in data science oriented tasks 
# support missing data
# Each column in a DataFrame is a Series 
# column may contain different element types 

In [4]:
import pandas as pd

In [5]:
grades_dict={'Wally':[87,96,70],'Eva':[100,87,90],'Sam':[94,77,90],'Katie':[100,81,82]
            ,'Bob':[83,65,85]}

In [6]:
grades_dict

{'Wally': [87, 96, 70],
 'Eva': [100, 87, 90],
 'Sam': [94, 77, 90],
 'Katie': [100, 81, 82],
 'Bob': [83, 65, 85]}

In [7]:
grades=pd.DataFrame(grades_dict) # convert Dictonary to dataframe

In [160]:
grades # since we havn't mentioned any index it creared with default 0 1 and 2 

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [ ]:
# we can create an index instead default values 

In [9]:
grades.index=['Test1','Test2','Test3']

In [162]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [163]:
# accessing dataframe columns 

In [164]:
grades['Eva'] # it returns the Eva column

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [165]:
grades.Eva # another way to access column 

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [166]:
# accessing row 

In [167]:
grades.loc['Test1']   # loc mean location  and we received in a Series format 

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [168]:
grades.iloc[1] # we can alos get the row by index number , in this case row 1 ( whcih mean row 2 , idex start from 0)
# so here it is iloc , not loc 
# iloc mean index location 

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [ ]:
# slicing in DataFrame

In [169]:
grades.loc['Test1':'Test3'] # note here in this DataFrame slice it include the last index too 

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [170]:
grades.iloc[0:2] # in this iloc it will not include the last index

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [171]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [172]:
grades.loc[['Test1','Test3']] # here we can include the list what multiple rows we nned [[]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [173]:
grades.iloc[[0,2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [ ]:
# access both subset of rows and column 

In [174]:
grades.loc['Test1':'Test2',['Eva','Katie']]
# here we are accessing two rows Test1 and Test2  and columns Eva and Katie 
# here we mentioned rows in slice , i.e   Test1 to Test2 and specific columns Eva and Katie 
# please note here the first argument is slice but could be list  and second argument is list but alos coulbe be slice

Eva  Katie
Test1  100    100
Test2   87     81

In [175]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [176]:
grades.iloc[[0,2],0:3]
# we specificly mentioned row 1 and 2 and column from 0 to 3 

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [177]:
# boolean indexing 

In [178]:
grades[grades>=90] # it check with each element that it is greater than or equal to 90 and retun the dataframe 
# which has values >=90 and those remaing element shown as NaN ( not a number ) ( like null in oracle )

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [179]:
grades[(grades>=80) & (grades<90)]  # we can evaluate multiple conditions 
# please note in pandas the and operator represent in & amd the or operator represent in |
# please note in standard python we mention AND and OR while checking conditions
# where as in Pandas we use these operators to check these AND and OR operators 

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [180]:
# some other attributes 

In [181]:
grades.at['Test2','Eva'] # to get the perticual elemnt ffrom the column and row 

87

In [182]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [183]:
grades.iat[2,0] # similar to above , here we mention index value 

70

In [185]:
# one advantege with at attribute is you can assign values to the particular element  in DF

In [186]:
grades.at['Test2','Eva']=100 # se here the value will change from 87 to 100

In [187]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96  100   77     81   65
Test3     70   90   90     82   85

In [188]:
# we can alos do this same by iat 

In [ ]:
# this at and iat attributes can bring only one element 

In [189]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96  100   77     81   65
Test3     70   90   90     82   85

In [190]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  87.000000   87.666667  77.666667
std    13.203535    5.773503   8.888194   10.692677  11.015141
min    70.000000   90.000000  77.000000   81.000000  65.000000
25%    78.500000   95.000000  83.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [194]:
pd.set_option('Precision', 2) # need to check why this error 
# basically it tries to set precision to 2 digit , which retuen 2 digit after . (dot )

OptionError: 'Pattern matched multiple keys'

In [195]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  87.000000   87.666667  77.666667
std    13.203535    5.773503   8.888194   10.692677  11.015141
min    70.000000   90.000000  77.000000   81.000000  65.000000
25%    78.500000   95.000000  83.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [196]:
grades.mean()

Wally    84.333333
Eva      96.666667
Sam      87.000000
Katie    87.666667
Bob      77.666667
dtype: float64

In [ ]:
# so far we are doing all the DF stats on the columns 
# we alos can do these on rows 
# we can do is tranpose(T) the DF (pivot) and do the descriptive stats 

In [197]:
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100    100     90
Sam       94     77     90
Katie    100     81     82
Bob       83     65     85

In [198]:
grades.T.describe()

Test1       Test2      Test3
count    5.000000    5.000000   5.000000
mean    92.800000   83.800000  83.400000
std      7.661593   14.307341   8.234076
min     83.000000   65.000000  70.000000
25%     87.000000   77.000000  82.000000
50%     94.000000   81.000000  85.000000
75%    100.000000   96.000000  90.000000
max    100.000000  100.000000  90.000000

In [199]:
grades.T.mean()  # please here the T is not creating new DF , it just a View 

Test1    92.8
Test2    83.8
Test3    83.4
dtype: float64

In [200]:
# sort the DF by usind Indicies 

In [201]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96  100   77     81   65
Test3     70   90   90     82   85

In [203]:
grades.sort_index(ascending=False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96  100   77     81   65
Test1     87  100   94    100   83

In [ ]:
# note here it order by idex element (row) , since ascending=False it order by descndng 
# thet is y we see rows descending i.e test3 test2 and test1 

In [ ]:
# sort the  columns 

In [204]:
grades.sort_index(axis=1) # here the axix=1 mean column

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65  100     81   77     96
Test3   85   90     82   90     70

In [205]:
# see the columns names it order by alphabatically 

In [1]:
# we not only sort the keys , we can also sort the data 

In [10]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [11]:
grades.sort_values(by='Test1',axis=1,ascending=False)
# here it sayinf order by  row Test1 ,axis=1 mean order by row ( default its column ) ascending=False
# mean order by descending

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2   87     81   77     96   65
Test3   90     82   90     70   85

In [12]:
grades.sort_values(by='Test2',axis=1,ascending=False)


Wally  Eva  Katie  Sam  Bob
Test1     87  100    100   94   83
Test2     96   87     81   77   65
Test3     70   90     82   90   85

In [14]:
grades.T.sort_values(by='Test2',ascending=False)
# notice here we didn't mentiond axis , as by defaylt it sort column wise 
# T : transcrive is to convert rows into columns 


Test1  Test2  Test3
Wally     87     96     70
Eva      100     87     90
Katie    100     81     82
Sam       94     77     90
Bob       83     65     85

In [18]:
# in the above result we see all the columns , instead if we want to see only Test2 
# we can use loc 

In [21]:
grades.loc['Test2'].sort_values(ascending=False)

Wally    96
Eva      87
Katie    81
Sam      77
Bob      65
Name: Test2, dtype: int64

In [22]:
# in the above  sorting it always create copy and sort the values , so it would be costly in terms of memory
# for large data sents 

In [23]:
# if we want to perform sort on the orginal DF we can inplace = True while sorting 

In [28]:
grades.sort_values(by='Test1' , axis=1,ascending=False , inplace=True)

In [ ]:
# END 